name: CI pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'chatbot/**'
      - '.github/workflows/ci_pipeline.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'chatbot/**'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Development

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check docker compose version
      run: |
        docker --version || true
